groups:
    type: rest
    resource: "SLNRegisterBundle:GroupeRest"
    name_prefix: api_

licensees:
    type: rest
    resource: "SLNRegisterBundle:LicenseeRest"
    name_prefix: api_

mail:
    type: rest
    resource: "SLNRegisterBundle:MailRest"
    name_prefix: api_


