services:
    sln_user.registration.form.type:
        class: SLN\RegisterBundle\Form\Type\RegistrationFormType
        tags:
            - {name: form.type, alias: sln_user_registration}
    sln_user.profile.form.type:
        class: SLN\RegisterBundle\Form\Type\ProfileFormType
        tags:
            - {name: form.type, alias: sln_user_profile}
    sln_register.form.type.horaire:
        class: SLN\RegisterBundle\Form\Type\HoraireType
        tags:
            - { name: form.type, alias: horaire }
#    sln_register.example:
#        class: SLN\RegisterBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    sln_register.upload_listener:
        class: SLN\RegisterBundle\EventListener\UploadListener
        arguments: 
            - "@doctrine.orm.entity_manager" 
            - "@security.context"
        tags:
            - { name: kernel.event_listener, event: oneup_uploader.post_upload, method: onUpload }

