services:
    sln_user.registration.form.type:
        class: SLN\RegisterBundle\Form\Type\RegistrationFormType
        tags:
            - {name: form.type, alias: sln_user_registration}
    sln_user.profile.form.type:
        class: SLN\RegisterBundle\Form\Type\ProfileFormType
        tags:
            - {name: form.type, alias: sln_user_profile}
    sln_register.form.type.horaire:
        class: SLN\RegisterBundle\Form\Type\HoraireType
        tags:
            - { name: form.type, alias: horaire }

    sln_register.upload_listener:
        class: SLN\RegisterBundle\EventListener\UploadListener
        arguments: 
            - "@doctrine.orm.entity_manager" 
            - "@security.context"
        tags:
            - { name: kernel.event_listener, event: oneup_uploader.post_upload, method: onUpload }

    sln_register.exception_listener:
        class: SLN\RegisterBundle\EventListener\ExceptionListener
        arguments:
            router: "@router"
            session: "@session"
        tags: 
            - { name: kernel.event_listener, event: kernel.exception }

    sln_register.maintenance_listener:
        class: SLN\RegisterBundle\EventListener\MaintenanceListener
        arguments:
            container: "@service_container"
        tags:
            - {name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

