services:
    sln_user.registration.form.type:
        class: SLN\RegisterBundle\Form\Type\RegistrationFormType
        tags:
            - {name: form.type, alias: sln_user_registration}
#    sln_register.example:
#        class: SLN\RegisterBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
